### PR TITLE
Migration project to TypeScript and added Dockerfile.

### PR DESCRIPTION
**Pull request by soyJDan**

### CODE REVIEW

**Comment by Dark-LYNN** [comment]
mind me asking:
1. Why use DockerFile?
2. why swap to ts?

**Comment by soyJDan** [comment]
**Answering the Dockerfile question:**
We have the ability to run multiple applications, which makes it easier for us to share our containers and speed up the maintenance and development process. This way, we can avoid the typical comment “it works on my machine” and be able to confirm that it works in a “production” environment.

**Answering the TypeScript question:**
In the package.json, I had the TypeScript dependency unused. Additionally, the ForgeScript project is made in TypeScript, this will help to solve possible conflicts or errors; and TypeScript is a rigid extension of JavaScript.

**Comment by soyJDan** [comment]
You can create a dev-typescript branch or another branch to save the project’s history.

**Comment by Dark-LYNN** [comment]
## About using Dockerfile:
> At this moment im still updating akira from its old package to ForgeScript, once this is done i will look into using Dockerfile.

## About using ts:
> Personally i have no experience with TS and i feel more comfortable with using JS the reason ts was as dependency was because it was needed in a previous version of ForgeScript.

**Comment by soyJDan** [comment]
I understand, I appreciate the time you took to review the pull request.

**Pull request closed without merging**
